<a href="https://colab.research.google.com/github/AntonySSk/Machine_Learning/blob/dev/%D0%9B%D0%911_%D0%A8%D0%BA%D0%BE%D0%BB%D0%B0_3_9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Лабораторна робота 1. NumPy

**Тема:** основи роботи з бібліотекою NumPy, масиви, вектори та матриці.

### Правила роботи
- Виконуйте завдання послідовно.
- Для обчислень використовуйте можливості **NumPy**.
- Не замінюйте операції NumPy звичайними Python-циклами, якщо це прямо не вказано в умові.
- Після виконання кожного завдання виводьте отриманий результат.


## 0. Підготовка середовища

### Завдання 0
Імпортуйте бібліотеку NumPy з псевдонімом `np`. Виведіть версію встановленої бібліотеки NumPy.

In [ ]:
# Код студента
import numpy as np

# Виведення версії встановленої бібліотеки NumPy
print(np.__version__)

2.1.3


## 1. Створення масивів NumPy

### Завдання 1
Створіть одновимірний NumPy-масив із чисел:
`[2, 4, 6, 8, 10]`.

Виведіть масив та його тип за допомогою `type()`.

In [ ]:
# Код студента
import numpy as np

# Створення одновимірного масиву з чисел: [2, 4, 6, 8, 10]
arr = np.array([2, 4, 6, 8, 10])

# Виведення масиву та його типу за допомогою type()
print("Масив:", arr)
print("Тип об'єкта:", type(arr))

Масив: [ 2  4  6  8 10]
Тип об'єкта: <class 'numpy.ndarray'>


### Завдання 2
Створіть:
1. масив із 10 нулів;
2. масив із 8 одиниць;
3. масив із 6 елементів, усі значення яких дорівнюють `7`.

Використайте відповідні функції NumPy.

In [ ]:
# Код студента
import numpy as np

# 1. Масив із 10 нулів
zeros_arr = np.zeros(10)

# 2. Масив із 8 одиниць
ones_arr = np.ones(8)

# 3. Масив із 6 елементів, усі значення яких дорівнюють 7
sevens_arr = np.full(6, 7)

print("1. Масив із 10 нулів:", zeros_arr)
print("2. Масив із 8 одиниць:", ones_arr)
print("3. Масив із 6 семірок:", sevens_arr)

1. Масив із 10 нулів: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
2. Масив із 8 одиниць: [1. 1. 1. 1. 1. 1. 1. 1.]
3. Масив із 6 семірок: [7 7 7 7 7 7]


### Завдання 3
Створіть масив цілих чисел від `1` до `20` включно.

Після цього створіть окремий масив парних чисел від `2` до `20`.

In [ ]:
# Код студента
import numpy as np

# Створення масиву цілих чисел від 1 до 20 включно
arr_all = np.arange(1, 21)

# Створення окремого масиву парних чисел від 2 до 20
arr_even = np.arange(2, 21, 2)

print("Масив чисел від 1 до 20:", arr_all)
print("Масив парних чисел від 2 до 20:", arr_even)

Масив чисел від 1 до 20: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Масив парних чисел від 2 до 20: [ 2  4  6  8 10 12 14 16 18 20]


### Завдання 4
За допомогою `np.linspace()` створіть масив із **11 рівновіддалених чисел** від `0` до `1` включно.

In [ ]:
# Код студента
import numpy as np

# Створення масиву з 11 рівновіддалених чисел від 0 до 1 включно
arr_lin = np.linspace(0, 1, 11)

print("Масив:", arr_lin)

Масив: [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


### Завдання 5
Створіть матрицю розміром `3 × 4`, заповнену числами від `1` до `12`.

Спочатку створіть одновимірний масив, а потім змініть його форму.

In [ ]:
# Код студента
import numpy as np

# Створення одновимірного масиву з числами від 1 до 12
arr_1d = np.arange(1, 13)

# Зміна форми масиву на матрицю розміром 3x4
matrix = arr_1d.reshape(3, 4)

print("Матриця 3x4:\n", matrix)

Матриця 3x4:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


## 2. Основні характеристики масивів

### Завдання 6
Для матриці, створеної у попередньому завданні, визначте та виведіть:
- кількість вимірів;
- форму;
- загальну кількість елементів;
- тип даних елементів.

Використайте атрибути `ndim`, `shape`, `size`, `dtype`.

In [ ]:
# Код студента
import numpy as np

# Матриця з попереднього завдання
matrix = np.arange(1, 13).reshape(3, 4)

# Визначення та виведення характеристик за допомогою атрибутів
print("Кількість вимірів (ndim):", matrix.ndim)
print("Форма (shape):", matrix.shape)
print("Загальна кількість елементів (size):", matrix.size)
print("Тип даних елементів (dtype):", matrix.dtype)

Кількість вимірів (ndim): 2
Форма (shape): (3, 4)
Загальна кількість елементів (size): 12
Тип даних елементів (dtype): int64


### Завдання 7
Створіть масив:
`[1.2, 3.5, 5.7, 7.9]`.

Перетворіть його елементи на цілі числа за допомогою `astype()` та виведіть новий масив.

In [ ]:
# Код студента
import numpy as np

# Створення масиву дробових чисел
float_arr = np.array([1.2, 3.5, 5.7, 7.9])

# Перетворення елементів на цілі числа
int_arr = float_arr.astype(int)

print("Новий масив (цілі числа):", int_arr)

Новий масив (цілі числа): [1 3 5 7]


## 3. Індексація та зрізи

### Завдання 8
Створіть масив:
`[10, 20, 30, 40, 50, 60, 70, 80]`.

Виведіть:
1. перший елемент;
2. останній елемент;
3. елементи з індексами від `2` до `5` включно;
4. кожен другий елемент.

In [ ]:
# Код студента
import numpy as np

# Створення масиву
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80])

# 1. Перший елемент
first_elem = arr[0]

# 2. Останній елемент
last_elem = arr[-1]

# 3. Елементи з індексами від 2 до 5 включно
slice_2_to_5 = arr[2:6]

# 4. Кожен другий елемент
every_second = arr[::2]

print("1. Перший елемент:", first_elem)
print("2. Останній елемент:", last_elem)
print("3. Елементи з індексами від 2 до 5 включно:", slice_2_to_5)
print("4. Кожен другий елемент:", every_second)

1. Перший елемент: 10
2. Останній елемент: 80
3. Елементи з індексами від 2 до 5 включно: [30 40 50 60]
4. Кожен другий елемент: [10 30 50 70]


### Завдання 9
Створіть матрицю:

```text
[[ 1,  2,  3,  4],
 [ 5,  6,  7,  8],
 [ 9, 10, 11, 12]]
```

Виведіть:
1. елемент `7`;
2. другий рядок;
3. третій стовпець;
4. підматрицю з останніх двох рядків і перших двох стовпців.

In [ ]:
# Код студента
import numpy as np

# Створення матриці
matrix = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

# 1. Елемент 7
elem_7 = matrix[1, 2]

# 2. Другий рядок
second_row = matrix[1]

# 3. Третій стовпець
third_col = matrix[:, 2]

# 4. Підматриця з останніх двох рядків і перших двох стовпців
submatrix = matrix[1:, :2]

print("1. Елемент 7:", elem_7)
print("2. Другий рядок:", second_row)
print("3. Третій стовпець:", third_col)
print("4. Підматриця (останні 2 рядки, перші 2 стовпці):\n", submatrix)

1. Елемент 7: 7
2. Другий рядок: [5 6 7 8]
3. Третій стовпець: [ 3  7 11]
4. Підматриця (останні 2 рядки, перші 2 стовпці):
 [[ 5  6]
 [ 9 10]]


### Завдання 10
Створіть масив чисел від `1` до `15`.

Замініть усі елементи з індексами від `5` до `9` включно на число `0`.

In [ ]:
# Код студента
import numpy as np

# Створення масиву чисел від 1 до 15
arr = np.arange(1, 16)

# Заміна елементів з індексами від 5 до 9 включно на число 0
arr[5:10] = 0

print("Оновлений масив:", arr)

Оновлений масив: [ 1  2  3  4  5  0  0  0  0  0 11 12 13 14 15]


## 4. Арифметичні операції та агрегатні функції

### Завдання 11
Створіть два масиви:

```python
a = [1, 2, 3, 4, 5]
b = [10, 20, 30, 40, 50]
```

Виконайте поелементно:
- додавання;
- віднімання;
- множення;
- ділення.

In [ ]:
# Код студента
import numpy as np

# Створення двох масивів
a = np.array([1, 2, 3, 4, 5])
b = np.array([10, 20, 30, 40, 50])

# Поелементні операції
add_res = a + b
sub_res = a - b
mul_res = a * b
div_res = a / b

print("Додавання:", add_res)
print("Віднімання:", sub_res)
print("Множення:", mul_res)
print("Ділення:", div_res)

Додавання: [11 22 33 44 55]
Віднімання: [ -9 -18 -27 -36 -45]
Множення: [ 10  40  90 160 250]
Ділення: [0.1 0.1 0.1 0.1 0.1]


### Завдання 12
Для масиву:

`[4, 8, 15, 16, 23, 42]`

обчисліть:
- суму;
- середнє значення;
- мінімум;
- максимум;
- медіану;
- стандартне відхилення.

In [ ]:
# Код студента
import numpy as np

# Створення масиву
arr = np.array([4, 8, 15, 16, 23, 42])

# Обчислення статистичних показників
total_sum = np.sum(arr)
mean_val = np.mean(arr)
min_val = np.min(arr)
max_val = np.max(arr)
median_val = np.median(arr)
std_val = np.std(arr)

print("Сума:", total_sum)
print("Середнє значення:", mean_val)
print("Мінімум:", min_val)
print("Максимум:", max_val)
print("Медіана:", median_val)
print("Стандартне відхилення:", std_val)

Сума: 108
Середнє значення: 18.0
Мінімум: 4
Максимум: 42
Медіана: 15.5
Стандартне відхилення: 12.315302134607444


### Завдання 13
Створіть матрицю:

```text
[[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]]
```

Обчисліть:
1. суму всіх елементів;
2. суму по кожному стовпцю;
3. суму по кожному рядку;
4. середнє значення по кожному стовпцю.

In [ ]:
# Код студента
import numpy as np

# Створення матриці
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# 1. Сума всіх елементів
total_sum = np.sum(matrix)

# 2. Сума по кожному стовпцю
col_sum = np.sum(matrix, axis=0)

# 3. Сума по кожному рядку
row_sum = np.sum(matrix, axis=1)

# 4. Середнє значення по кожному стовпцю
col_mean = np.mean(matrix, axis=0)

print("1. Сума всіх елементів:", total_sum)
print("2. Сума по кожному стовпцю:", col_sum)
print("3. Сума по кожному рядку:", row_sum)
print("4. Середнє значення по кожному стовпцю:", col_mean)

1. Сума всіх елементів: 45
2. Сума по кожному стовпцю: [12 15 18]
3. Сума по кожному рядку: [ 6 15 24]
4. Середнє значення по кожному стовпцю: [4. 5. 6.]


### Завдання 14
Для масиву чисел від `1` до `10` обчисліть:
- квадрат кожного елемента;
- квадратний корінь кожного елемента;
- натуральний логарифм кожного елемента.

Використайте функції NumPy.

In [ ]:
# Код студента
import numpy as np

# Створення масиву чисел від 1 до 10
arr = np.arange(1, 11)

# Обчислення квадрата кожного елемента
squares = np.square(arr)  # або arr ** 2

# Обчислення квадратного кореня кожного елемента
sqrts = np.sqrt(arr)

# Обчислення натурального логарифма кожного елемента
logs = np.log(arr)

print("Квадрати:", squares)
print("Квадратні корені:", sqrts)
print("Натуральні логарифми:", logs)

Квадрати: [  1   4   9  16  25  36  49  64  81 100]
Квадратні корені: [1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.         3.16227766]
Натуральні логарифми: [0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458 2.30258509]


## 5. Логічні операції та фільтрація

### Завдання 15
Створіть масив:

`[3, 7, 12, 18, 21, 25, 30, 34]`

За допомогою булевої маски виведіть:
1. усі числа, більші за `15`;
2. усі парні числа;
3. числа в діапазоні від `10` до `30` включно.

In [ ]:
# Код студента
import numpy as np

# Створення масиву
arr = np.array([3, 7, 12, 18, 21, 25, 30, 34])

# 1. Усі числа, більші за 15
greater_than_15 = arr[arr > 15]

# 2. Усі парні числа
even_numbers = arr[arr % 2 == 0]

# 3. Числа в діапазоні від 10 до 30 включно
range_10_30 = arr[(arr >= 10) & (arr <= 30)]

print("1. Усі числа, більші за 15:", greater_than_15)
print("2. Усі парні числа:", even_numbers)
print("3. Числа в діапазоні від 10 до 30 включно:", range_10_30)

1. Усі числа, більші за 15: [18 21 25 30 34]
2. Усі парні числа: [12 18 30 34]
3. Числа в діапазоні від 10 до 30 включно: [12 18 21 25 30]


### Завдання 16
Для масиву:

`[-5, 3, -2, 8, -1, 10, 0]`

замініть усі від’ємні значення на `0`.

Не використовуйте цикл `for`.

In [ ]:
# Код студента
import numpy as np

# Створення масиву
arr = np.array([-5, 3, -2, 8, -1, 10, 0])

# Заміна всіх від'ємних значень на 0 за допомогою булевої маски (без циклу for)
arr[arr < 0] = 0

print("Оновлений масив:", arr)

Оновлений масив: [ 0  3  0  8  0 10  0]


### Завдання 17
Створіть масив випадкових цілих чисел від `0` до `100` розміром `20`.

Порахуйте:
- скільки елементів більші за `50`;
- скільки елементів менші або дорівнюють `50`.

Для відтворюваності встановіть `np.random.seed(42)`.

In [ ]:
# Код студента
import numpy as np

# Встановлення зерна генератора для відтворюваності
np.random.seed(42)

# Створення масиву випадкових цілих чисел від 0 до 100 розміром 20
arr = np.random.randint(0, 101, size=20)

# Підрахунок кількості елементів
count_greater_50 = np.sum(arr > 50)
count_less_equal_50 = np.sum(arr <= 50)

print("Масив:", arr)
print("Кількість елементів більших за 50:", count_greater_50)
print("Кількість елементів менших або рівних 50:", count_less_equal_50)

Масив: [51 92 14 71 60 20 82 86 74 74 87 99 23  2 21 52  1 87 29 37]
Кількість елементів більших за 50: 12
Кількість елементів менших або рівних 50: 8


## 6. Зміна форми та об'єднання масивів

### Завдання 18
Створіть масив чисел від `1` до `24`.

Перетворіть його:
1. у матрицю `4 × 6`;
2. у матрицю `6 × 4`;
3. у тривимірний масив форми `2 × 3 × 4`.

Після кожного перетворення виведіть `shape`.

In [ ]:
# Код студента
import numpy as np

# Створення масиву чисел від 1 до 24
arr = np.arange(1, 25)

# 1. Матриця 4x6
mat_4x6 = arr.reshape(4, 6)
print("1. Матриця 4x6:\n", mat_4x6)
print("Форма (shape):", mat_4x6.shape)

# 2. Матриця 6x4
mat_6x4 = arr.reshape(6, 4)
print("\n2. Матриця 6x4:\n", mat_6x4)
print("Форма (shape):", mat_6x4.shape)

# 3. Тривимірний масив форми 2x3x4
arr_3d = arr.reshape(2, 3, 4)
print("\n3. Тривимірний масив 2x3x4:\n", arr_3d)
print("Форма (shape):", arr_3d.shape)

1. Матриця 4x6:
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]
Форма (shape): (4, 6)

2. Матриця 6x4:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]
Форма (shape): (6, 4)

3. Тривимірний масив 2x3x4:
 [[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
Форма (shape): (2, 3, 4)


### Завдання 19
Створіть дві матриці:

```text
A = [[1, 2],
     [3, 4]]

B = [[5, 6],
     [7, 8]]
```

Об’єднайте їх:
1. вертикально;
2. горизонтально.

Використайте функції NumPy.

In [ ]:
# Код студента
import numpy as np

# Створення двох матриць
A = np.array([
    [1, 2],
    [3, 4]
])

B = np.array([
    [5, 6],
    [7, 8]
])

# 1. Вертикальне об'єднання
v_stacked = np.vstack((A, B))  # або np.concatenate((A, B), axis=0)

# 2. Горизонтальне об'єднання
h_stacked = np.hstack((A, B))  # або np.concatenate((A, B), axis=1)

print("1. Вертикально:\n", v_stacked)
print("\n2. Горизонтально:\n", h_stacked)

1. Вертикально:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]

2. Горизонтально:
 [[1 2 5 6]
 [3 4 7 8]]


### Завдання 20
Створіть матрицю `3 × 4` із числами від `1` до `12`.

Перетворіть її назад в одновимірний масив двома способами:
- за допомогою `flatten()`;
- за допомогою `ravel()`.

Порівняйте результати.

In [ ]:
# Код студента
import numpy as np

# Створення матриці 3x4 із числами від 1 до 12
matrix = np.arange(1, 13).reshape(3, 4)

# 1. За допомогою flatten() (повертає копію масиву)
flat_arr = matrix.flatten()

# 2. За допомогою ravel() (повертає в'ю/представлення, якщо це можливо)
raveled_arr = matrix.ravel()

print("Оригінальна матриця:\n", matrix)
print("\n1. Результат flatten():", flat_arr)
print("2. Результат ravel():", raveled_arr)
print("Чи однакові результати за значеннями?:", np.array_equal(flat_arr, raveled_arr))

Оригінальна матриця:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

1. Результат flatten(): [ 1  2  3  4  5  6  7  8  9 10 11 12]
2. Результат ravel(): [ 1  2  3  4  5  6  7  8  9 10 11 12]
Чи однакові результати за значеннями?: True


## 7. Дії з векторами

### Завдання 21
Дано два вектори:

```text
a = [2, 4, 6]
b = [1, 3, 5]
```

Знайдіть:
- суму векторів;
- різницю векторів;
- результат множення кожного вектора на число `3`.

In [ ]:
# Код студента
import numpy as np

# Дані вектори
a = np.array([2, 4, 6])
b = np.array([1, 3, 5])

# Обчислення
sum_vec = a + b
diff_vec = a - b
mul_a = a * 3
mul_b = b * 3

print("Сума векторів:", sum_vec)
print("Різниця векторів:", diff_vec)
print("Результат множення вектора 'a' на 3:", mul_a)
print("Результат множення вектора 'b' на 3:", mul_b)

Сума векторів: [ 3  7 11]
Різниця векторів: [1 1 1]
Результат множення вектора 'a' на 3: [ 6 12 18]
Результат множення вектора 'b' на 3: [ 3  9 15]


### Завдання 22
Для векторів:

```text
a = [1, 2, 3]
b = [4, 5, 6]
```

Обчисліть їх **скалярний добуток** двома способами:
1. за допомогою `np.dot()`;
2. за допомогою оператора `@`.

In [ ]:
# Код студента
import numpy as np

# Створення векторів
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# 1. Скалярний добуток за допомогою np.dot()
dot_1 = np.dot(a, b)

# 2. Скалярний добуток за допомогою оператора @
dot_2 = a @ b

print("1. Скалярний добуток (np.dot):", dot_1)
print("2. Скалярний добуток (оператор @):", dot_2)

1. Скалярний добуток (np.dot): 32
2. Скалярний добуток (оператор @): 32


### Завдання 23
Для вектора:

```text
v = [3, 4]
```

обчисліть його евклідову норму.

Потім нормалізуйте вектор, тобто отримайте вектор одиничної довжини.

In [ ]:
# Код студента
import numpy as np

# Креирање на векторот
v = np.array([3, 4])

# Пресметување на Евклидовата норма (должина на векторот)
norm = np.linalg.norm(v)

# Нормализација на векторот (вектор со единична должина)
normalized_v = v / norm

print("Евклидова норма:", norm)
print("Нормализиран вектор:", normalized_v)

Евклидова норма: 5.0
Нормализиран вектор: [0.6 0.8]


### Завдання 24
Дано вектори:

```text
a = [1, 0, 0]
b = [0, 1, 0]
```

Знайдіть їх векторний добуток за допомогою `np.cross()`.

In [ ]:
# Код студента
import numpy as np

# Створення векторів
a = np.array([1, 0, 0])
b = np.array([0, 1, 0])

# Векторний добуток за допомогою np.cross()
cross_prod = np.cross(a, b)

print("Векторний добуток:", cross_prod)

Векторний добуток: [0 0 1]


### Завдання 25
Дано два вектори:

```text
a = [1, 2]
b = [2, 1]
```

Обчисліть косинус кута між ними за формулою через скалярний добуток і норми векторів.

Додатково знайдіть сам кут у градусах.

In [ ]:
# Код студента
import numpy as np

# Створення векторів
a = np.array([1, 2])
b = np.array([2, 1])

# Обчислення скалярного добутку та норм векторів
dot_prod = np.dot(a, b)
norm_a = np.linalg.norm(a)
norm_b = np.linalg.norm(b)

# Обчислення косинуса кута між векторами
cos_angle = dot_prod / (norm_a * norm_b)

# Знаходження кута у радіанах та переведення в градуси
angle_rad = np.arccos(cos_angle)
angle_deg = np.degrees(angle_rad)

print("Косинус кута:", cos_angle)
print("Кут у градусах:", angle_deg)

Косинус кута: 0.7999999999999998
Кут у градусах: 36.86989764584404


## 8. Дії з матрицями

### Завдання 26
Дано матрицю:

```text
A = [[1, 2, 3],
     [4, 5, 6]]
```

Знайдіть транспоновану матрицю двома способами:
1. за допомогою `.T`;
2. за допомогою `np.transpose()`.

In [ ]:
# Код студента
import numpy as np

# Створення матриці
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

# 1. Транспонування за допомогою атрибута .T
A_transposed_1 = A.T

# 2. Транспонування за допомогою функції np.transpose()
A_transposed_2 = np.transpose(A)

print("Оригінальна матриця:\n", A)
print("\n1. Транспонована (.T):\n", A_transposed_1)
print("\n2. Транспонована (np.transpose):\n", A_transposed_2)

Оригінальна матриця:
 [[1 2 3]
 [4 5 6]]

1. Транспонована (.T):
 [[1 4]
 [2 5]
 [3 6]]

2. Транспонована (np.transpose):
 [[1 4]
 [2 5]
 [3 6]]


### Завдання 27
Дано матриці:

```text
A = [[1, 2],
     [3, 4]]

B = [[2, 0],
     [1, 2]]
```

Обчисліть:
1. поелементний добуток `A * B`;
2. матричний добуток `A @ B`.

Поясніть у коментарі до коду, чим відрізняються ці операції.

In [ ]:
# Код студента
import numpy as np

# Створення матриць
A = np.array([
    [1, 2],
    [3, 4]
])

B = np.array([
    [2, 0],
    [1, 2]
])

# 1. Поелементний добуток (Hadamard product)
elementwise_mult = A * B

# 2. Матричний добуток (класичне множення матриць "рядок на стовпець")
matrix_mult = A @ B  # або np.matmul(A, B)

print("1. Поелементний добуток (A * B):\n", elementwise_mult)
print("\n2. Матричний добуток (A @ B):\n", matrix_mult)

# Пояснення:
# A * B перемножує елементи, які стоять на однакових позиціях (наприклад, A[0,0] * B[0,0]).
# A @ B виконує скалярний добуток рядків матриці A на стовпці матриці B за правилами лінійної алгебри.

1. Поелементний добуток (A * B):
 [[2 0]
 [3 8]]

2. Матричний добуток (A @ B):
 [[ 4  4]
 [10  8]]


### Завдання 28
Для матриці:

```text
A = [[4, 7],
     [2, 6]]
```

обчисліть:
- визначник;
- обернену матрицю.

Перевірте результат, помноживши початкову матрицю на обернену.

In [ ]:
# Код студента
import numpy as np

# Створення матриці
A = np.array([
    [4, 7],
    [2, 6]
])

# Обчислення визначника (детермінанта)
det_A = np.linalg.det(A)

# Обчислення оберненої матриці
inv_A = np.linalg.inv(A)

# Перевірка: множення початкової матриці на обернену (має вийти одинична матриця)
identity_check = A @ inv_A

print("Визначник матриці A:", det_A)
print("\nОбернена матриця A^-1:\n", inv_A)
print("\nПеревірка (A @ A^-1):\n", identity_check)

Визначник матриці A: 10.000000000000002

Обернена матриця A^-1:
 [[ 0.6 -0.7]
 [-0.2  0.4]]

Перевірка (A @ A^-1):
 [[ 1.00000000e+00 -1.11022302e-16]
 [ 1.11022302e-16  1.00000000e+00]]


### Завдання 29
Розв’яжіть систему лінійних рівнянь за допомогою NumPy:

```text
2x +  y = 5
 x + 3y = 6
```

Сформуйте матрицю коефіцієнтів `A` і вектор правих частин `b`.

Використайте `np.linalg.solve()`.

In [ ]:
# Код студента
import numpy as np

# Матриця коефіцієнтів A та вектор правих частин b
A = np.array([
    [2, 1],
    [1, 3]
])

b = np.array([5, 6])

# Розв'язання системи лінійних рівнянь
x = np.linalg.solve(A, b)

print("Розв'язок системи (x, y):", x)

Розв'язок системи (x, y): [1.8 1.4]


### Завдання 30
Створіть одиничну матрицю розміром `4 × 4`.

Перевірте властивість одиничної матриці: помножте на неї довільну матрицю `4 × 4` та порівняйте результат з початковою матрицею.

In [ ]:
# Код студента
import numpy as np

# Створення одиничної матриці розміром 4x4
I = np.eye(4)

# Створення довільної матриці 4x4 (наприклад, із послідовними числами)
A = np.arange(1, 17).reshape(4, 4)

# Множення довільної матриці на одиничну
result = A @ I

print("Одинична матриця I:\n", I)
print("\nПочаткова матриця A:\n", A)
print("\nРезультат множення A @ I:\n", result)
print("\nЧи збігається результат із початковою матрицею?:", np.array_equal(A, result))

Одинична матриця I:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

Початкова матриця A:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Результат множення A @ I:
 [[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]
 [13. 14. 15. 16.]]

Чи збігається результат із початковою матрицею?: True


## 9. Broadcasting (операція трансляції)

### Завдання 31
Створіть матрицю:

```text
A = [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]]
```

Додайте число `10` до кожного її елемента.

In [ ]:
# Код студента
import numpy as np

# Створення матриці A
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# Додавання числа 10 до кожного елемента (використання трансляції / broadcasting)
result = A + 10

print("Початкова матриця A:\n", A)
print("\nРезультат додавання 10:\n", result)

Початкова матриця A:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Результат додавання 10:
 [[11 12 13]
 [14 15 16]
 [17 18 19]]


### Завдання 32
До матриці:

```text
A = [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]]
```

додайте вектор:

```text
v = [10, 20, 30]
```

Проаналізуйте, як NumPy застосував broadcasting.

In [ ]:
# Код студента
import numpy as np

# Створення матриці A та вектора v
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

v = np.array([10, 20, 30])

# Додавання вектора до кожного рядка матриці за допомогою broadcasting
result = A + v

print("Матриця A:\n", A)
print("\nВектор v:\n", v)
print("\nРезультат (A + v):\n", result)

# Пояснення broadcasting:
# Вектор v (форма (3,)) автоматично транслюється вздовж першої осі (axis 0),
# розширюючись до форми (3, 3), та додається до кожного рядка матриці A.

Матриця A:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Вектор v:
 [10 20 30]

Результат (A + v):
 [[11 22 33]
 [14 25 36]
 [17 28 39]]


### Завдання 33
Нормалізуйте **кожен стовпець** матриці:

```text
A = [[10, 20, 30],
     [20, 30, 40],
     [30, 40, 50]]
```

за формулою:

\[
z = \frac{x - \mu}{\sigma}
\]

де `μ` — середнє значення стовпця, `σ` — стандартне відхилення стовпця.

Не використовуйте цикл `for`.

In [ ]:
# Код студента
import numpy as np

# Створення матриці A
A = np.array([
    [10, 20, 30],
    [20, 30, 40],
    [30, 40, 50]
])

# Середнє значення та стандартне відхилення для кожного стовпця (axis=0)
mu = np.mean(A, axis=0)
sigma = np.std(A, axis=0)

# Нормалізація за допомогою broadcasting (без циклу for)
Z = (A - mu) / sigma

print("Середнє значення стовпців (mu):", mu)
print("Стандартне відхилення стовпців (sigma):", sigma)
print("\nНормалізована матриця (Z):\n", Z)

Середнє значення стовпців (mu): [20. 30. 40.]
Стандартне відхилення стовпців (sigma): [8.16496581 8.16496581 8.16496581]

Нормалізована матриця (Z):
 [[-1.22474487 -1.22474487 -1.22474487]
 [ 0.          0.          0.        ]
 [ 1.22474487  1.22474487  1.22474487]]


## 10. Випадкові дані

### Завдання 34
Встановіть `np.random.seed(42)` та створіть:
1. 10 випадкових цілих чисел від `1` до `100`;
2. матрицю `3 × 3` випадкових чисел від `0` до `1`;
3. 1000 значень із нормального розподілу.

Для третього масиву обчисліть середнє та стандартне відхилення.

In [ ]:
# Код студента
import numpy as np

# Поставување на random seed за повторливост на резултатите
np.random.seed(42)

# 1. 10 случајни цели броеви од 1 до 100
rand_integers = np.random.randint(1, 101, size=10)

# 2. Матрица 3x3 со случајни броеви од 0 до 1
rand_matrix = np.random.rand(3, 3)

# 3. 1000 вредности од стандардна нормална распределба
rand_normal = np.random.randn(1000)

# Пресметување на средна вредност и стандардно отстапување за третиот низа
mean_val = np.mean(rand_normal)
std_val = np.std(rand_normal)

print("1. 10 случајни цели броеви (1-100):\n", rand_integers)
print("\n2. Матрица 3x3 со броеви од 0 до 1:\n", rand_matrix)
print("\n3. Средна вредност за нормалната распределба:", mean_val)
print("   Стандардно отстапување:", std_val)

1. 10 случајни цели броеви (1-100):
 [52 93 15 72 61 21 83 87 75 75]

2. Матрица 3x3 со броеви од 0 до 1:
 [[0.86617615 0.60111501 0.70807258]
 [0.02058449 0.96990985 0.83244264]
 [0.21233911 0.18182497 0.18340451]]

3. Средна вредност за нормалната распределба: 0.02216865975826456
   Стандардно отстапување: 0.9792284455184356


### Завдання 35
Змоделюйте оцінки 30 студентів — випадкові цілі числа від `0` до `100`.

Визначте:
- середню оцінку;
- медіану;
- найвищу та найнижчу оцінки;
- кількість студентів, які отримали не менше `60`;
- відсоток студентів, які отримали не менше `90`.

In [ ]:
# Код студента
import numpy as np

# Фіксація генератора випадкових чисел для відтворюваності результатів
np.random.seed(42)

# Моделювання оцінок 30 студентів (цілі числа від 0 до 100)
scores = np.random.randint(0, 101, size=30)

# 1. Середня оцінка
mean_score = np.mean(scores)

# 2. Медіана
median_score = np.median(scores)

# 3. Найвища та найнижча оцінки
max_score = np.max(scores)
min_score = np.min(scores)

# 4. Кількість студентів з оцінкою не менше 60
count_60_or_more = np.sum(scores >= 60)

# 5. Відсоток студентів з оцінкою не менше 90
percentage_90_or_more = np.mean(scores >= 90) * 100

print("Оцінки студентів:\n", scores)
print("\nСередня оцінка:", mean_score)
print("Медіана:", median_score)
print(f"Найвища оцінка: {max_score}, найнижча оцінка: {min_score}")
print("Кількість студентів з оцінкою >= 60:", count_60_or_more)
print(f"Відсоток студентів з оцінкою >= 90: {percentage_90_or_more:.2f}%")

Оцінки студентів:
 [51 92 14 71 60 20 82 86 74 74 87 99 23  2 21 52  1 87 29 37  1 63 59 20
 32 75 57 21 88 48]

Середня оцінка: 50.86666666666667
Медіана: 54.5
Найвища оцінка: 99, найнижча оцінка: 1
Кількість студентів з оцінкою >= 60: 13
Відсоток студентів з оцінкою >= 90: 6.67%


## 11. Підсумкові завдання

### Завдання 36
Дано результати продажів трьох товарів за чотири місяці:

```text
sales = [[120, 150, 170, 160],
         [80,  90,  100, 110],
         [200, 180, 210, 230]]
```

Рядки — товари, стовпці — місяці.

Визначте:
1. загальний обсяг продажів кожного товару;
2. загальний обсяг продажів у кожному місяці;
3. товар із найбільшими сумарними продажами;
4. місяць із найбільшим загальним обсягом продажів;
5. середній обсяг продажів кожного товару.

In [ ]:
# Код студента
import numpy as np

# Створення матриці продажів (рядки — товари, стовпці — місяці)
sales = np.array([
    [120, 150, 170, 160],
    [80, 90, 100, 110],
    [200, 180, 210, 230]
])

# 1. Загальний обсяг продажів кожного товару (сума за рядками)
sales_per_product = np.sum(sales, axis=1)

# 2. Загальний обсяг продажів у кожному місяці (сума за стовпцями)
sales_per_month = np.sum(sales, axis=0)

# 3. Товар із найбільшими сумарними продажами (індекс + 1)
best_product_idx = np.argmax(sales_per_product) + 1

# 4. Місяць із найбільшим загальним обсягом продажів (індекс + 1)
best_month_idx = np.argmax(sales_per_month) + 1

# 5. Середній обсяг продажів кожного товару (середнє за рядками)
avg_sales_per_product = np.mean(sales, axis=1)

print("1. Загальний обсяг продажів кожного товару:", sales_per_product)
print("2. Загальний обсяг продажів у кожному місяці:", sales_per_month)
print(f"3. Товар із найбільшими продажами: Товар №{best_product_idx}")
print(f"4. Місяць із найбільшим обсягом продажів: Місяць №{best_month_idx}")
print("5. Середній обсяг продажів кожного товару:", avg_sales_per_product)

1. Загальний обсяг продажів кожного товару: [600 380 820]
2. Загальний обсяг продажів у кожному місяці: [400 420 480 500]
3. Товар із найбільшими продажами: Товар №3
4. Місяць із найбільшим обсягом продажів: Місяць №4
5. Середній обсяг продажів кожного товару: [150.  95. 205.]


### Завдання 37
Створіть квадратну матрицю `5 × 5` із випадкових цілих чисел від `1` до `20`.

Виконайте:
1. знайдіть суму головної діагоналі;
2. знайдіть суму побічної діагоналі;
3. знайдіть максимальний елемент кожного рядка;
4. знайдіть мінімальний елемент кожного стовпця;
5. замініть усі елементи, менші за середнє значення всієї матриці, на `0`.

In [ ]:
# Код студента
import numpy as np

# Створення матриці продажів (рядки — товари, стовпці — місяці)
sales = np.array([
    [120, 150, 170, 160],
    [80, 90, 100, 110],
    [200, 180, 210, 230]
])

# 1. Загальний обсяг продажів кожного товару (сума за рядками)
sales_per_product = np.sum(sales, axis=1)

# 2. Загальний обсяг продажів у кожному місяці (сума за стовпцями)
sales_per_month = np.sum(sales, axis=0)

# 3. Товар із найбільшими сумарними продажами (індекс + 1)
best_product_idx = np.argmax(sales_per_product) + 1

# 4. Місяць із найбільшим загальним обсягом продажів (індекс + 1)
best_month_idx = np.argmax(sales_per_month) + 1

# 5. Середній обсяг продажів кожного товару (середнє за рядками)
avg_sales_per_product = np.mean(sales, axis=1)

print("1. Загальний обсяг продажів кожного товару:", sales_per_product)
print("2. Загальний обсяг продажів у кожному місяці:", sales_per_month)
print(f"3. Товар із найбільшими продажами: Товар №{best_product_idx}")
print(f"4. Місяць із найбільшим обсягом продажів: Місяць №{best_month_idx}")
print("5. Середній обсяг продажів кожного товару:", avg_sales_per_product)

1. Загальний обсяг продажів кожного товару: [600 380 820]
2. Загальний обсяг продажів у кожному місяці: [400 420 480 500]
3. Товар із найбільшими продажами: Товар №3
4. Місяць із найбільшим обсягом продажів: Місяць №4
5. Середній обсяг продажів кожного товару: [150.  95. 205.]


### Завдання 38
Дано матрицю ознак трьох об’єктів:

```text
X = [[2, 4, 6],
     [1, 3, 5],
     [5, 7, 9]]
```

Обчисліть **евклідову відстань** між:
- першим і другим рядком;
- першим і третім рядком;
- другим і третім рядком.

Використайте операції NumPy та `np.linalg.norm()`.

In [ ]:
# Код студента
import numpy as np

# Створення матриці ознак
X = np.array([
    [2, 4, 6],
    [1, 3, 5],
    [5, 7, 9]
])

# Обчислення евклідової відстані між рядками за допомогою np.linalg.norm()
dist_1_2 = np.linalg.norm(X[0] - X[1])
dist_1_3 = np.linalg.norm(X[0] - X[2])
dist_2_3 = np.linalg.norm(X[1] - X[2])

print("Евклідова відстань між 1-м та 2-м рядком:", dist_1_2)
print("Евклідова відстань між 1-м та 3-м рядком:", dist_1_3)
print("Евклідова відстань між 2-м та 3-м рядком:", dist_2_3)

Евклідова відстань між 1-м та 2-м рядком: 1.7320508075688772
Евклідова відстань між 1-м та 3-м рядком: 5.196152422706632
Евклідова відстань між 2-м та 3-м рядком: 6.928203230275509


### Завдання 39
Створіть матрицю `4 × 4` із довільних цілих чисел.

Для кожного рядка знайдіть його норму та створіть нову матрицю, у якій кожен рядок нормалізований до одиничної довжини.

Спробуйте виконати завдання без циклів.

In [ ]:
# Код студента
import numpy as np

# Фіксація генератора випадкових чисел для відтворюваності результатів
np.random.seed(42)

# Створення матриці 4x4 із довільних цілих чисел
matrix = np.random.randint(1, 10, size=(4, 4))

# Обчислення норми кожного рядка (axis=1, keepdims=True для зручного broadcasting)
row_norms = np.linalg.norm(matrix, axis=1, keepdims=True)

# Нормалізація кожного рядка до одиничної довжини без використання циклів
normalized_matrix = matrix / row_norms

print("Початкова матриця 4x4:\n", matrix)
print("\nНорми рядків:\n", row_norms)
print("\nНормалізована матриця (довжина кожного рядка = 1):\n", normalized_matrix)

# Перевірка: норми рядків нормалізованої матриці мають дорівнювати 1
print("\nПеревірка норм нормалізованих рядків:", np.linalg.norm(normalized_matrix, axis=1))

Початкова матриця 4x4:
 [[7 4 8 5]
 [7 3 7 8]
 [5 4 8 8]
 [3 6 5 2]]

Норми рядків:
 [[12.40967365]
 [13.07669683]
 [13.        ]
 [ 8.60232527]]

Нормалізована матриця (довжина кожного рядка = 1):
 [[0.56407607 0.32232919 0.64465837 0.40291148]
 [0.53530338 0.22941573 0.53530338 0.61177529]
 [0.38461538 0.30769231 0.61538462 0.61538462]
 [0.34874292 0.69748583 0.58123819 0.23249528]]

Перевірка норм нормалізованих рядків: [1. 1. 1. 1.]


### Завдання 40
Створіть матрицю коефіцієнтів і вектор правих частин для системи:

```text
 x + 2y +  z =  9
2x +  y -  z =  8
3x -  y + 2z =  3
```

1. Розв’яжіть систему за допомогою `np.linalg.solve()`.
2. Перевірте знайдений розв’язок матричним множенням `A @ x`.
3. Порівняйте результат із вектором `b`.

In [ ]:
# Код студента
import numpy as np

# Створення матриці коефіцієнтів A та вектора правих частин b
A = np.array([
    [1, 2, 1],
    [2, 1, -1],
    [3, -1, 2]
])

b = np.array([9, 8, 3])

# 1. Розв'язання системи за допомогою np.linalg.solve()
x = np.linalg.solve(A, b)

# 2. Перевірка знайденого розв'язку матричним множенням A @ x
b_check = A @ x

# 3. Порівняння результату з вектором b
are_equal = np.allclose(b_check, b)

print("Розв'язок системи (x, y, z):", x)
print("Результат множення A @ x:", b_check)
print("Вектор b:", b)
print("Чи збігається результат із вектором b?:", are_equal)

Розв'язок системи (x, y, z): [ 2.22222222  3.44444444 -0.11111111]
Результат множення A @ x: [9. 8. 3.]
Вектор b: [9 8 3]
Чи збігається результат із вектором b?: True


---

## Самоперевірка

Після виконання роботи студент повинен уміти:
- створювати та перетворювати NumPy-масиви;
- використовувати індексацію та зрізи;
- виконувати векторизовані арифметичні операції;
- застосовувати агрегатні функції;
- використовувати булеві маски;
- змінювати форму та об'єднувати масиви;
- виконувати основні дії з векторами;
- виконувати основні операції з матрицями;
- застосовувати broadcasting;
- використовувати функції `numpy.linalg` для задач лінійної алгебри.
